blueprint:
  name: "â„ï¸ðŸ”¥ Smart HVAC Interlock & State Manager"
  description: >-
    # ðŸ  Advanced Climate & Window Interlock
    
    This blueprint transforms your HVAC into a "Living System" that reacts intelligently to doors and windows. It solves the complex problem of managing heating (Winter) and cooling (Summer) with different logic strategies.
    
    **Version 1.1** includes a robust "Clean Slate" memory system that prevents errors when multiple windows are opened sequentially and fixes trace errors.

    ---
    
    ### âš™ï¸ Key Features
    * **â„ï¸ Winter Mode (Heating):** Switches your KNX/Thermostat to a safe preset (e.g., `Building Protection`) when windows open. It remembers your previous mode (`Comfort`, `Eco`, etc.) and restores it only when *all* windows close.
    * **ðŸ”¥ Summer Mode (Cooling):** Cuts power to AC units to save energy. It remembers if the AC was actually running and only turns it back on if it was previously active.
    * **ðŸ§  First-In Memory:** Prevents "State Amnesia." If you open Window A (saving 'Comfort' mode), then open Window B, the system is smart enough NOT to overwrite the memory with the current 'Protection' mode.
    * **ðŸ›¡ï¸ Zigbee Filter:** Ignores brief `unavailable` states common in Zigbee meshes to prevent ghost switching.

    ---

    ### ðŸ“‹ Requirements (Create these Helpers first!)
    1. **Season Switch** (`input_boolean`):
       * `On` = Summer (Cooling Logic)
       * `Off` = Winter (Heating Logic)
    2. **Winter Memory** (`input_text`):
       * Stores the name of the heating preset (e.g., 'comfort').
    3. **Summer Memory** (`input_boolean`):
       * Stores the state of the AC (On/Off).

    ---
    
    *Version 1.1 - Architect Grade*

  domain: automation
  input:
    opening_sensors:
      name: ðŸšª Opening Sensors
      description: Select all windows/doors in this zone. The automation waits for ALL to close before resuming HVAC.
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: [window, door, garage_door, opening]
    
    season_selector:
      name: ðŸŒ¤ï¸ Season Selector
      description: Helper to switch logic. ON = Summer, OFF = Winter.
      selector:
        entity:
          domain: input_boolean
            
    # --- WINTER CONFIG ---
    winter_climate_device:
      name: â„ï¸ Winter Climate Entity
      description: The thermostat/valve to control in Winter.
      selector:
        entity:
          domain: climate
    
    winter_last_state_helper:
      name: (Winter) Memory Helper
      description: "REQUIRED: An `input_text` helper to store the previous preset name."
      selector:
        entity:
          domain: input_text

    winter_safe_preset:
      name: (Winter) Open Preset (Safe Mode)
      description: The mode to apply while windows are OPEN (e.g., 'Building Protection' or 'Off').
      selector:
        select:
          options:
            - "building_protection"
            - "eco"
            - "away"
            - "off"
          custom_value: true
      default: "building_protection"

    # --- SUMMER CONFIG ---
    summer_climate_device:
      name: ðŸ”¥ Summer Climate Entity
      description: The AC unit to control in Summer.
      selector:
        entity:
          domain: climate

    summer_last_state_helper:
      name: (Summer) Memory Helper
      description: "REQUIRED: An `input_boolean` helper to remember if the AC was running."
      selector:
        entity:
          domain: input_boolean

    # --- TIMING ---
    open_delay:
      name: â±ï¸ Open Delay
      description: Seconds to wait before cutting HVAC (prevents false triggers/fluttering).
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    close_delay:
      name: â±ï¸ Close Delay
      description: Seconds to wait after ALL windows are closed before resuming HVAC.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds

variables:
  season_selector: !input season_selector
  winter_device: !input winter_climate_device
  summer_device: !input summer_climate_device
  winter_helper: !input winter_last_state_helper
  summer_helper: !input summer_last_state_helper
  is_summer: "{{ is_state(season_selector, 'on') }}"
  opening_sensors: !input opening_sensors

trigger:
  - platform: state
    entity_id: !input opening_sensors
    to: "on"
    for: !input open_delay
    id: "opened"
  - platform: state
    entity_id: !input opening_sensors
    to: "off"
    for: !input close_delay
    id: "closed"

mode: single

action:
  - choose:
      # ----------------------------------------------------------------
      # SCENARIO: A SENSOR OPENED
      # ----------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "opened"
        sequence:
          - choose:
              # --- WINTER OPEN LOGIC ---
              - conditions: "{{ not is_summer }}"
                sequence:
                  # MEMORY CHECK: Only save if the helper is currently EMPTY/UNKNOWN.
                  # This means it's the first window to open.
                  - if:
                      - condition: template
                        value_template: "{{ states(winter_helper) in ['unknown', 'unavailable', ''] }}"
                    then:
                      - action: input_text.set_value
                        target:
                          entity_id: !input winter_last_state_helper
                        data:
                          value: "{{ state_attr(winter_device, 'preset_mode') | default('comfort') }}"
                  
                  # Apply Safe Mode (Always apply this to ensure safety)
                  - action: climate.set_preset_mode
                    target:
                      entity_id: !input winter_climate_device
                    data:
                      preset_mode: !input winter_safe_preset

              # --- SUMMER OPEN LOGIC ---
              - conditions: "{{ is_summer }}"
                sequence:
                  # MEMORY CHECK: Only save if helper is OFF (Clean state)
                  - if:
                      - condition: state
                        entity_id: !input summer_last_state_helper
                        state: "off"
                    then:
                      - action: input_boolean.turn_{{ 'on' if not is_state(summer_device, 'off') else 'off' }}
                        target:
                          entity_id: !input summer_last_state_helper
                  
                  # Turn off AC if it's running
                  - if:
                      - condition: template
                        value_template: "{{ not is_state(summer_device, 'off') }}"
                    then:
                      - action: climate.turn_off
                        target:
                          entity_id: !input summer_climate_device

      # ----------------------------------------------------------------
      # SCENARIO: A SENSOR CLOSED
      # ----------------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "closed"
          # Double check: Are ALL sensors actually closed?
          - condition: template
            value_template: >
              {{ expand(opening_sensors) | selectattr('state', 'eq', 'on') | list | count == 0 }}
        sequence:
          - choose:
              # --- WINTER CLOSE LOGIC ---
              - conditions: "{{ not is_summer }}"
                sequence:
                  # Restore from Helper
                  - if:
                      - condition: template
                        value_template: "{{ states(winter_helper) not in ['unknown', 'unavailable', ''] }}"
                    then:
                      - action: climate.set_preset_mode
                        target:
                          entity_id: !input winter_climate_device
                        data:
                          preset_mode: "{{ states(winter_helper) }}"
                  
                  # CLEANUP: Wipe the helper so it's ready for the next cycle
                  - action: input_text.set_value
                    target:
                      entity_id: !input winter_last_state_helper
                    data:
                      value: ""

              # --- SUMMER CLOSE LOGIC ---
              - conditions: "{{ is_summer }}"
                sequence:
                  - if:
                      - condition: state
                        entity_id: !input summer_last_state_helper
                        state: "on"
                    then:
                      - action: climate.turn_on
                        target:
                          entity_id: !input summer_climate_device
                  
                  # CLEANUP: Turn off the helper
                  - action: input_boolean.turn_off
                    target:
                      entity_id: !input summer_last_state_helper
